TRAIN:
  ENABLE: True
  DATASET: Skeleton
  BATCH_SIZE: 16
  IS_VALIDATION: True
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3, 3, 3]
DETECTION:
  ENABLE: False
  ALIGNED: True
SKELETON:
  TRAIN_DATA_PATH: "data/NTU-RGB-D/xsub/train_data.npy"
  TEST_DATA_PATH: "data/NTU-RGB-D/xsub/val_data.npy"
  TRAIN_LABEL_FILE: "data/NTU-RGB-D/xsub/train_label.pkl"
  TEST_LABEL_FILE: "data/NTU-RGB-D/xsub/val_label.pkl"
  PERSON_NUM_OUT: 5
  MAX_FRAME: 150
  GRAPH_ARGS:
    LAYOUT: "ntu-rgb+d"
    STRATEGY: "spatial"
MULTIGRID:
  SHORT_CYCLE: False
  LONG_CYCLE: False
SLOWFAST:
  ALPHA: 8
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3, 3], [4, 4, 4], [6, 6, 6], [3, 3, 3]]
  SPATIAL_DILATIONS: [[1, 1, 1], [1, 1, 1], [1, 1, 1], [2, 2, 2]]
  SPATIAL_STRIDES: [[1, 1, 1], [2, 2, 2], [2, 2, 2], [1, 1, 1]]
NONLOCAL:
  LOCATION: [[[], [], []], [[], [], []], [[], [], []], [[], [], []]]
  GROUP: [[1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1]]
  INSTANTIATION: dot_product
  POOL: [[[1, 2, 2], [1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2], [1, 2, 2]]]
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.4
  LR_DECAY: 0.4
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 10, 15, 20]
  LRS: [1, 0.1, 0.01, 0.001]
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-7
  WARMUP_EPOCHS: 5.0
  WARMUP_START_LR: 0.000125
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 60
  ARCH: sf_gcn
  MODEL_NAME: SF_GCN
  LOSS_FUNC: bce
  DROPOUT_RATE: 0.5
  HEAD_ACT: sigmoid
TEST:
  ENABLE: False # changed from True
  DATASET: skeleton
  BATCH_SIZE: 2 # changed from 8
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True
NUM_GPUS: 2
NUM_SHARDS: 1
OUTPUT_DIR: .
